#!/bin/sh
# Regenerate nife's C library headers (`vendor/relibc/include`) from the seeded relibc modules
# (milestone 835 (a C library, stage 1: files, clock and memory)). Not run by any gate: the headers
# are committed, and this is how they were made and how a change to a seeded module's exported types
# reaches them.
#
# relibc generates each header from its module's Rust with cbindgen, one `cbindgen.toml` per
# module plus `cbindgen.globdefs.toml` (relibc's Makefile, `headers` target). This is that loop,
# unchanged apart from the paths. The headers that are not generated (`stdint.h`, `features.h`,
# `sys/param.h` and the rest) are relibc's `include/` as seeded, and this leaves them alone.
#
# It needs cbindgen 0.29.0 on PATH (`cargo install cbindgen --version 0.29.0 --locked`), the version
# the committed headers came from. cbindgen is a tool run by hand, not a build dependency: no build
# of nife invokes it, which is why a §46 (thin primitives or whole subsystems; we write everything
# in between) ruling on it is asked for rather than assumed.
#
# Usage: helpers/c-library-headers.sh            every seeded module with a cbindgen.toml
#        helpers/c-library-headers.sh math stdio  just these
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SEED="$ROOT/vendor/relibc"
command -v cbindgen >/dev/null || { echo "c-library-headers: no cbindgen on PATH" >&2; exit 1; }
cd "$SEED/header"
if [ $# -eq 0 ]; then
  for d in */; do
    if [ -f "$d/cbindgen.toml" ]; then set -- "$@" "${d%/}"; fi
  done
fi
for h in "$@"; do
  # `sys_stat` is `sys/stat.h`, `bits_clock-t` is `bits/clock-t.h`, as relibc names them.
  out="$SEED/include/$(echo "$h" | sed 's/_/\//g').h"
  mkdir -p "$(dirname "$out")"
  cat "$h/cbindgen.toml" "$SEED/cbindgen.globdefs.toml" \
    | cbindgen "$h/mod.rs" --config=/dev/stdin --output "$out" 2>&1 | grep -v '^WARN' || true
  # The provenance line §265 (a C library started from relibc) asks of every seeded file, which cbindgen cannot write itself
  # because the module configs are relibc's.
  { echo "/* Generated by helpers/c-library-headers.sh from vendor/relibc/header/$h, seeded from relibc (MIT) at 893a3b9133ac (vendor/README.md). Edit the module, not this file. */"
    cat "$out"; } > "$out.tmp" && mv "$out.tmp" "$out"
done
